vich_uploader:
    db_driver: orm

    mappings:
        drivers_avatar:
            uri_prefix: '%app.path.driver.avatar%'
            upload_destination: '%kernel.project_dir%/public%app.path.driver.avatar%'
        team_race_car:
            uri_prefix: '%app.path.team.race.car%'
            upload_destination: '%kernel.project_dir%/public%app.path.team.race.car%'
        drivers_modal_avatar:
            uri_prefix: '%app.path.driver.modal%'
            upload_destination: '%kernel.project_dir%/public%app.path.driver.modal%'

