vich_uploader:
    db_driver: orm

    mappings:
        drivers_avatar:
            uri_prefix: '%app.path.driver.avatar%'
            upload_destination: '%kernel.project_dir%/public%app.path.driver.avatar%'
