#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register_controller:
  path: /register
  controller: App\Controller\RegistrationController::registerAction

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
